### PR TITLE
Several bug fixes

### LINKED ISSUE #14: Bug in server install script: } instead of fi
Line 38 to 41:

```
if [ "$4" = "yes" ] ;then
    inst dnsutils
    inst lynx
}
```

### LINKED ISSUE #15: Server install script should check for root access
The script cannot install packages if not run as root or run with sudo.

### LINKED ISSUE #17: Script cannot create database configuration if folder does not exist
If the directories /var/www/bis and /var/www/bis/config do not exist, the script will not write the database settings. The directories should be created by the script.

### LINKED ISSUE #18: Detection of PHP is not so robust
```
if [ "`php -v | grep PHP | grep 7.0 | wc -l`" -eq "1" ] ;then
```

should probably be

```
if [ "`php -v | grep "PHP 7.0" | wc -l`" -eq "1" ] ;then
```

### LINKED ISSUE #19: Git cannot be installed on Raspberry Pi
On Raspbian 2020-03, Git cannot be installed until `sudo apt update` was run.
Perhaps this command should be integrated.

### LINKED ISSUE #20: Repository cannot be cloned because directory is not empty
It seems that the order of steps is not good. The repository should be cloned before writing mySQL config data into it.

### LINKED ISSUE #21: Weather server cannot be found
The script tries to access /var/www/bis/weather/... but it should have /server/ in its path.

### PR DESCRIPTION
**Pull request by thomasw-mitutoyo-ctl**
Fix #14: } instead of fi
Fix #15: Server install script should check for root access
Fix #17: Script cannot create database configuration if folder does not exist
Fix #18: Detection of PHP is not so robust
Fix #19: Git cannot be installed on Raspberry Pi
Fix #20: Repository cannot be cloned because directory is not empty
Fix #21: Weather server cannot be found
Fix bugs in documentation / enhance documentation

### CODE REVIEW

File: server/install.sh [hunk 1]
```diff
@@ -64,6 +94,7 @@ if [ -f /var/www/bis/config/db_settings.ini ] ;then
 else
 	err "Database settings are not configured"
 	doing "Configuring ..."
+	mkdir /var/www/bis/config
```
Comment (thomasw-mitutoyo-ctl) [inline server/install.sh]: This could miss a /server/ in the path. But that's potentially fixed by #24. Just make sure the conflicts are resolved correctly.

**Review by thomasw-mitutoyo-ctl — COMMENTED** [review]
Go ahead and solve the conflicts
